Default: &defaults
  database: sqliteNeuLadderPost.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: sqliteNeuLadderPost_test.sqlite3
  <<: *defaults

Staging:
  database: sqliteNeuLadderPost_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: /opt/keter/database/sqliteNeuLadderPost_production.sqlite3
  poolsize: 100
  <<: *defaults
